Repository milovangudelj/scacchiera, pull requests merged in 2022-01, with the labels that each got.

#31 Player class improved
  include/Player.h
  src/player.cpp
Labels: enhancement

#33 Player improvement and partial testing, Utilities operators
  CMakeLists.txt
  include/Player.h
  include/Utilities.h
  src/player.cpp
  src/targets/test.cpp
  src/utilities.cpp
Labels: enhancement

#47 added nullptr check for the eventual rook, and check if the rook is t…
  src/pieces/king.cpp
Labels: bug fix

#52 Added `replay` target skeleton
  CMakeLists.txt
  src/targets/replay.cpp
Labels: new feature

#57 Controller `replay()` implementation
  include/Board.h
  src/board.cpp
  src/controller.cpp
Labels: enhancement

#59 Switch to regular pointers
  include/Board.h
  include/Controller.h
  include/Player.h
  src/board.cpp
  src/controller.cpp
  src/pieces/bishop.cpp
  src/pieces/king.cpp
  src/pieces/knight.cpp
  src/pieces/pawn.cpp
  src/pieces/queen.cpp
  src/pieces/rook.cpp
  src/player.cpp
Labels: enhancement

#63 Small fixes
  include/Board.h
  include/Piece.h
  src/board.cpp
  src/controller.cpp
Labels: bug fix

#64 promotion
  include/Controller.h
  include/Coordinate.h
  src/board.cpp
  src/controller.cpp
  src/coordinate.cpp
  src/player.cpp
  src/targets/test.cpp
Labels: enhancement

#67 Added promotion for computer
  include/Board.h
  include/Controller.h
  src/board.cpp
  src/controller.cpp
  src/targets/test.cpp
Labels: enhancement

#69 Changed controller for new replay args and prom
  CMakeLists.txt
  include/Controller.h
  src/board.cpp
  src/controller.cpp
  src/targets/replay.cpp
  src/targets/scacchiera.cpp
Labels: enhancement

#66 Build type relwithdebuginfo
  CMakeLists.txt
Labels: new feature

#70 Fixing cursors and output/file printing
  p_vs_c_example_2.txt
  src/controller.cpp
  src/targets/replay.cpp
Labels: bug fix

#74 Added documentation comments for my files
  include/Controller.h
  include/Player.h
  include/Utilities.h
  include/pieces/Bishop.h
  include/pieces/Queen.h
  src/board.cpp
  src/controller.cpp
  src/pieces/bishop.cpp
  src/pieces/queen.cpp
  src/player.cpp
  src/targets/scacchiera.cpp
Labels: documentation, enhancement
